apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    appName: {{ .Values.metadata.appName }}
    projectName: {{ .Chart.Name }}
spec:
  {{- if .Values.initContainers.enabled }}
  volumes:
   - name: vault-secret
     emptyDir: { }
  initContainers:
    - name: get-secrets
      image: docker.io/pavanidevops78/kubernetes:1.6
      env:
        - name: VAULT_ADDR
          value: https://vault-internal.pdevops72.online:8200
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/vault
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
      volumeMounts:
        - name: vault-secret
          mountPath: /data
    - name: schema
      image: pavanidevops78/kubernetes:2.2
      volumeMounts:
        - name: vault-secret
          mountPath: /data
 {{- end }}

  containers:
    - name: {{ .Values.containers.name }}
      image: pavanidevops78/kubernetes:{{ .Values.dockerImageVersion }}
      {{- if .Values.initContainers.enabled }}
      volumeMounts:
        - name: vault-secret
          mountPath: /data
      {{- end }}



