apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.metadata.component }}
  labels:
    appName: {{ .Values.metadata.project_name }}
    projectName: {{ .Chart.Name }}
    appVersion: {{ .Values.metadata.appVersion }}
spec:
  {{- if .Values.initContainers.enabled }}
  volumes:
   - name: vault-secret
     emptyDir: { }
  initContainers:
    - name: get-secrets
      image: public.ecr.aws/u4j6q5s8/kubernetes-vault-init-container:1.2
      env:
        - name: VAULT_ADDR
          value: https://vault-internal.pdevops72.online:8200
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: common/vault
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
      volumeMounts:
        - name: vault-secret
          mountPath: /data
    - name: schema
      image: public.ecr.aws/u4j6q5s8/backend-schema:1.4
      volumeMounts:
        - name: vault-secret
          mountPath: /data
 {{- end }}

  containers:
    - name: {{ .Values.containers.name }}
      image: public.ecr.aws/u4j6q5s8/{{ .Values.metadata.project_name }}-{{ .Values.metadata.component }}:1.0
      {{- if .Values.initContainers.enabled }}
      volumeMounts:
        - name: vault-secret
          mountPath: /data
      {{- end }}


#public.ecr.aws/u4j6q5s8/expense-backend:1.0
#public.ecr.aws/u4j6q5s8/expense-backend:1.1

#public.ecr.aws/u4j6q5s8/expense-backend:1.4
