apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.component }}
spec:
  selector:
    appName: {{ .Values.selector.appName }}
    projectName: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
  type: {{ .Values.selector.type }}



#  ExpenseApp123----DB_PASS
#expense----DB_USER
